#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "model_dvm_reader.h"  // generated by flatcc
#include "model_dvm_verifier.h"


#define ns(x) FLATBUFFERS_WRAP_NAMESPACE(ARA2_Model, x)

int main() {
    // Read the buffer from file
    FILE *fp = fopen("model.bin", "rb");
    if (!fp) {
        perror("Failed to open model.bin");
        return 1;
    }

    fseek(fp, 0, SEEK_END);
    size_t size = ftell(fp);
    rewind(fp);

    uint8_t *buffer = malloc(size);
    if (!buffer) {
        perror("Failed to allocate buffer");
        fclose(fp);
        return 1;
    }

    fread(buffer, 1, size, fp);
    fclose(fp);

    // Verify the buffer
    if (!ns(Model_verify_as_root(buffer, size))) {
        fprintf(stderr, "Invalid FlatBuffer format\n");
        free(buffer);
        return 1;
    }

    // Read the root table
    ns(Model_table_t) model = ns(Model_as_root(buffer));
    if (!model) {
        fprintf(stderr, "❌ Failed to get root Model table\n");
        free(buffer);
        return 1;
    }
    // Access aligned struct fields
    ns(Model_a)(model);
    // ns(align16_t) b = ns(Model_b)(model);
    // ns(align32_t) c = ns(Model_c)(model);

    // // Print results
    // printf("a.x = 0x%02X\n", (*a)->x);
    // printf("b.x = 0x%02X\n", (*b)->x);
    // printf("c.x = 0x%02X\n", (*c)->x);
    

    free(buffer);
    return 0;
}
