#include <stdio.h>


#include "model_dvm_builder.h" // Generated by `flatcc`.
#include "model_dvm_reader.h" // Generated by `flatcc`.

#undef ns
#define ns(x) FLATBUFFERS_WRAP_NAMESPACE(Tanveer_Model,x)
#define c_vec_len(V) (sizeof(V)/sizeof((V)[0]))

flatcc_builder_t builder, *B;



int main(int argc, char**argv){
    
    B = &builder;
    flatcc_builder_init(B);

    Tanveer_Model_ScalarTable_ref_t ScalarTable_ = Tanveer_Model_ScalarTable_create(B, 0xaa, 0xbb);
    Tanveer_Model_ScalarStruct_t *ScalarStruct_ = Tanveer_Model_ScalarStruct_assign(ScalarStruct_, 0xaa, flatbuffers_true);
    Tanveer_Model_AllTable_ref_t AllTable_ = Tanveer_Model_AllTable_create_as_root(B, ScalarTable_, ScalarStruct_);

    size_t size;
    void *buf;

    buf = flatcc_builder_finalize_buffer(B, &size);

    FILE *fp = fopen("model.dvm", "wb");
    if(fp){
        fwrite(buf, 1, size, fp);
        fclose(fp);
    }
    else{
        perror("Error failed to open model.dvm file to write\n");
        return -1;
    }
    flatcc_builder_clear(B);

    fp = fopen("model.dvm", "rb");
    if(!fp){
        perror("Error failed to open model.dvm file to read\n");
        return -1;
    }
    fseek(fp, 0, SEEK_END);
    size = ftell(fp);
    rewind(fp);
    uint8_t *buffer = malloc(size);
    if(!buffer){
        perror("Malloc allocation failed");
        fclose(fp);
        return -1;
    }
    if (fread(buffer, 1, size, fp) != size) {
        perror("Failed to read file");
        free(buffer);
        fclose(fp);
        return 1;
    }
    // Deserialize the root
    ns(AllTable_table_t) all_table = ns(AllTable_as_root(buffer));
    if (!all_table) {
        fprintf(stderr, "Invalid buffer or root\n");
        free(buffer);
        return 1;
    }

    // Access ScalarTable
    ns(ScalarTable_table_t) scalar_table = ns(AllTable_iScalarTable(all_table));
    if (!scalar_table) {
        fprintf(stderr, "ScalarTable missing\n");
        free(buffer);
        return 1;
    }

    int8_t ibyte = ns(ScalarTable_ibyte(scalar_table));
    printf("ibyte = %d (0x%02x)\n", ibyte, (unsigned char)ibyte);

    free(buffer);
    return 0;
}